### ISSUE TITLE
the radio traces to the antenna 

### ISSUE THREAD

**Issue by OwenBrotherwood** [lrnzzz/RN2483-LoRa-Shield#1]
In connection with Gonzalos email
"the radio traces to the antenna are supposed to follow a very specific curve according to the RN2483's datasheet, and I'm not sure if your pcb has that."
As a tracker so that all comments can be in one place and not emails :)

---

Edit:
For quick click to what Gonzalos is refering to http://ww1.microchip.com/downloads/en/DeviceDoc/50002346A.pdf

Edit
Probably this
![image](https://cloud.githubusercontent.com/assets/866122/22655486/97f10818-ec90-11e6-8542-1748aee3282c.png)

**Comment by lrnzzz** [comment]
I think the way the traces to the antenna go is not important. It's just important you don't use sharp corners and you need to use strip lines with an 50 Ohm impedance. I tried to do these things. 

Maybe are there some other opinions?

**Comment by OwenBrotherwood** [comment]
I do not know enough on the subject: what is important for me is if something is mentioned, then you get a good feedback.
Perhaps a call out on https://thethingsnetwork.slack.com/messages/hardware/details/ and try and close the issue with feedback?

**Comment by OwenBrotherwood** [comment]
Just to keep in same place, a pic of the pcb 
No sharp corners so should be ok
And the tip is very direct
I will not be using "Lo", so is there any need for a "Lo" in another version of the board: I have no preference as I believe I only need "Hi"
![image](https://cloud.githubusercontent.com/assets/866122/22664367/aca784e2-ecb0-11e6-909a-0ca8f92a6240.png)

Edit:
But maybe others use "Lo" ...
